export const spacing = {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    screenPadding: 20,
    cardPadding: 16,
    gutter: 12,
    borderRadius: 16,
    borderRadiusSm: 10,
    borderRadiusLg: 24,
    borderRadiusFull: 999,
};
